import argparse
import sys
import re
import shutil
from pathlib import Path

DEFAULT_OUTPUT_NAME = "frontend_split_package"
DEFAULT_FRONTEND_VERSION = "v0.0.0"


def _normalize_api_base(api_base: str) -> str:
    value = str(api_base or "").strip()
    if not value:
        return ""
    if not re.match(r"^https?://", value, flags=re.IGNORECASE):
        raise ValueError("后端地址必须以 http:// 或 https:// 开头")
    return value.rstrip("/")


def _normalize_admin_api_prefix(admin_api_prefix: str) -> str:
    value = str(admin_api_prefix or "").strip()
    if not value:
        return ""
    if not value.startswith("/"):
        value = "/" + value
    if not value.startswith("/api/"):
        value = "/api" + value
    parts = [p for p in value.split("/") if p]
    normalized = "/" + "/".join(parts)
    if normalized in {"/", "/api"}:
        raise ValueError("admin API 前缀不能为 / 或 /api")
    if not re.match(r"^/[A-Za-z0-9/_-]+$", normalized):
        raise ValueError("admin API 前缀仅允许字母、数字、/、_、-")
    return normalized


def _inject_html_runtime_vars(html_path: Path, api_base: str, admin_api_prefix: str = "") -> None:
    if not html_path.exists():
        return
    original = html_path.read_text(encoding="utf-8")
    cleaned = re.sub(
        r"\s*<!--\s*Generated by scripts/package_frontend\.py\s*-->\s*<script>[\s\S]*?</script>\s*",
        "\n",
        original,
        flags=re.IGNORECASE,
    )
    lines = []
    if api_base:
        lines.append(f'window.__API_PREFIX__ = "{api_base}";')
    if admin_api_prefix:
        lines.append(f'window.__ADMIN_API_PREFIX_HINT__ = "{admin_api_prefix}";')

    if not lines:
        html_path.write_text(cleaned, encoding="utf-8")
        return

    script_body = "\n".join(lines)
    inject_block = (
        f'<!-- Generated by scripts/package_frontend.py -->\n'
        f"<script>\n{script_body}\n</script>\n"
    )
    head_open = re.search(r"<head[^>]*>", cleaned, flags=re.IGNORECASE)
    if head_open:
        insert_at = head_open.end()
        patched = f"{cleaned[:insert_at]}\n{inject_block}{cleaned[insert_at:]}"
    elif "</head>" in cleaned:
        patched = cleaned.replace("</head>", inject_block + "</head>", 1)
    else:
        patched = inject_block + cleaned
    html_path.write_text(patched, encoding="utf-8")


def _extract_frontend_version(frontend_dir: Path) -> str:
    index_path = frontend_dir / "index.html"
    if not index_path.exists():
        return ""
    content = index_path.read_text(encoding="utf-8")
    match = re.search(r"frontendVersion:\s*'([^']+)'", content)
    if not match:
        return ""
    return str(match.group(1) or "").strip()


def _normalize_version_tag(version: str) -> str:
    value = str(version or "").strip()
    if not value:
        return DEFAULT_FRONTEND_VERSION
    if not value.lower().startswith("v"):
        value = "v" + value
    # keep archive filename cross-platform safe
    value = re.sub(r"[^A-Za-z0-9._-]+", "_", value).strip("._-")
    return value or DEFAULT_FRONTEND_VERSION


def _build_archive_name(output_name: str, version: str) -> str:
    base = str(output_name or "").strip() or DEFAULT_OUTPUT_NAME
    normalized_version = _normalize_version_tag(version)
    if re.search(rf"[-_]{re.escape(normalized_version)}$", base):
        return base
    return f"{base}-{normalized_version}"


def _normalize_admin_path(admin_path: str) -> str:
    value = str(admin_path or "admin").strip().strip("/").strip()
    if not value:
        return "admin"
    if not re.match(r"^[A-Za-z0-9_\-]+$", value):
        raise ValueError("admin 路径仅允许字母、数字、下划线和中划线")
    return value


def _apply_admin_path(target_dir: Path, admin_path: str) -> None:
    if admin_path == "admin":
        return
    src = target_dir / "admin"
    dst = target_dir / admin_path
    if not src.exists():
        raise FileNotFoundError(f"未找到默认后台目录: {src}")
    if dst.exists():
        shutil.rmtree(dst)
    src.rename(dst)


def _write_deploy_readme(target_dir: Path, api_base: str, admin_path: str, admin_api_prefix: str = "") -> None:
    text = (
        "# 前端分离部署说明\n\n"
        "1. 将本目录全部文件上传到任意静态服务器（Nginx/CDN/对象存储网站托管均可）。\n"
        f"2. 默认首页为 index.html，管理后台入口为 {admin_path}/index.html。\n"
        "3. 当前包已固定后端地址：\n"
        f"   {api_base or '（未固定，使用前端默认自动识别逻辑）'}\n"
        "4. 当前包后台 API 前缀：\n"
        f"   {admin_api_prefix or '（未固定，默认自动推断/读取后台配置）'}\n"
        "5. 注意：本脚本只修改前端静态文件，不会修改后端运行时的 admin 路由配置。\n"
        "   若后端通过 backend/data/admin_panel_path.json 与 admin_api_prefix.json 自定义了路由，请保持与前端一致。\n"
        "6. 如果后端启用了跨域限制，请在后端 CORS 中放行此前端域名。\n"
    )
    (target_dir / "DEPLOY_FRONTEND.md").write_text(text, encoding="utf-8")


def package_frontend(api_base: str = "", output_name: str = DEFAULT_OUTPUT_NAME, admin_path: str = "admin", admin_api_prefix: str = "") -> None:
    base_dir = Path(__file__).resolve().parent.parent
    frontend_dir = base_dir / "frontend"
    dist_dir = base_dir / "dist"
    output_dir = dist_dir / "frontend_split"

    if not frontend_dir.exists():
        raise FileNotFoundError(f"frontend 目录不存在: {frontend_dir}")

    if output_dir.exists():
        shutil.rmtree(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    shutil.copytree(frontend_dir, output_dir, dirs_exist_ok=True)

    _apply_admin_path(output_dir, admin_path)

    public_html_targets = [
        output_dir / "index.html",
        output_dir / "lhb.html",
        output_dir / "help.html",
    ]
    for html in public_html_targets:
        _inject_html_runtime_vars(html, api_base, "")

    admin_html = output_dir / admin_path / "index.html"
    _inject_html_runtime_vars(admin_html, api_base, admin_api_prefix)

    _write_deploy_readme(output_dir, api_base, admin_path, admin_api_prefix)

    frontend_version = _extract_frontend_version(frontend_dir)
    archive_name = _build_archive_name(output_name, frontend_version)
    archive_base = dist_dir / archive_name
    archive_path = shutil.make_archive(str(archive_base), "zip", root_dir=str(output_dir))

    print("=" * 60)
    print("前端分离部署包已生成")
    print(f"输出目录：{output_dir}")
    print(f"压缩包：{archive_path}")
    print(f"后端地址：{api_base or '（自动识别默认逻辑）'}")
    print(f"后台目录：{admin_path}")
    print(f"管理员API前缀：{admin_api_prefix or '（自动推断默认逻辑）'}")
    print("=" * 60)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="打包可分离部署的前端，并可注入后端 API 地址。"
    )
    parser.add_argument(
        "--api-base",
        dest="api_base",
        default="",
        help="后端 API 基地址，例如 https://api.example.com 或 http://1.2.3.4:8000",
    )
    parser.add_argument(
        "--output-name",
        dest="output_name",
        default=DEFAULT_OUTPUT_NAME,
        help="输出 zip 文件名（不含 .zip）",
    )
    parser.add_argument(
        "--admin-path",
        dest="admin_path",
        default="admin",
        help="管理后台目录名，默认 admin。示例: admin-panel",
    )
    parser.add_argument(
        "--admin-api-prefix",
        dest="admin_api_prefix",
        default="",
        help="管理员 API 前缀，默认自动推断。示例: /api/admin-panel",
    )
    parser.add_argument(
        "--interactive",
        dest="interactive",
        action="store_true",
        help="交互模式：逐项输入后端地址、后台目录与管理员API前缀",
    )
    return parser.parse_args()


def _prompt_line(prompt: str) -> str:
    try:
        return input(prompt)
    except EOFError:
        return ""


def _collect_interactive_inputs() -> tuple[str, str, str, str]:
    print("=" * 60)
    print("前端分离打包交互模式")
    print("- 后端 API 地址：留空则使用默认自动识别逻辑")
    print("- 后台目录：留空则使用 admin")
    print("- 管理员 API 前缀：留空则使用默认自动推断逻辑")
    print(f"- 输出包名称：留空则使用 {DEFAULT_OUTPUT_NAME}")
    print("=" * 60)

    api_base = _prompt_line("请输入后端 API 地址（可留空）：").strip()
    admin_path = _prompt_line("请输入后台目录名（默认 admin）：").strip() or "admin"
    admin_api_prefix = _prompt_line("请输入管理员 API 前缀（可留空）：").strip()
    output_name = _prompt_line(f"请输入输出压缩包名（默认 {DEFAULT_OUTPUT_NAME}）：").strip() or DEFAULT_OUTPUT_NAME
    return api_base, admin_path, admin_api_prefix, output_name


if __name__ == "__main__":
    args = parse_args()
    interactive_mode = bool(args.interactive or len(sys.argv) == 1)

    if interactive_mode:
        raw_api_base, raw_admin_path, raw_admin_api_prefix, raw_output_name = _collect_interactive_inputs()
    else:
        raw_api_base = args.api_base
        raw_admin_path = args.admin_path
        raw_admin_api_prefix = args.admin_api_prefix
        raw_output_name = args.output_name

    normalized = _normalize_api_base(raw_api_base)
    normalized_admin_path = _normalize_admin_path(raw_admin_path)
    normalized_admin_api_prefix = _normalize_admin_api_prefix(raw_admin_api_prefix)

    package_frontend(
        api_base=normalized,
        output_name=str(raw_output_name or DEFAULT_OUTPUT_NAME),
        admin_path=normalized_admin_path,
        admin_api_prefix=normalized_admin_api_prefix,
    )
